package com.example.rubymod.entity.client;

import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.KeyframeAnimations;
import net.minecraft.client.animation.Keyframe;

public class ElephantAnimations {
        public static final AnimationDefinition WALKING = AnimationDefinition.Builder.withLength(2f).looping()
        .addAnimation("bone",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone3",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 1f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone8",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone8",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone9",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone9",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone10",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone10",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone11",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone11",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone12",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone12",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone13",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone13",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone4",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone14",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone14",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone15",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(2f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone15",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(2f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR))).build();
        public static final AnimationDefinition ATTACK = AnimationDefinition.Builder.withLength(1f).looping()
        .addAnimation("bone6",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone5",
                new AnimationChannel(AnimationChannel.Targets.POSITION, 
                        new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(0.5f, KeyframeAnimations.posVec(0f, 0f, -1f),
                                AnimationChannel.Interpolations.LINEAR), 
                        new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR)))
        .addAnimation("bone5",
                new AnimationChannel(AnimationChannel.Targets.ROTATION,
                        new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(0.5f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR),
                        new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
                                AnimationChannel.Interpolations.LINEAR))).build();
}
